development:
  adapter: postgresql
  database: monster_development
  pool: 5
  timeout: 5000
  username: monster

test:
  adapter: postgresql
  database: monster_test
  pool: 5
  timeout: 5000
  username: monster

production:
  adapter: postgresql
  encoding: utf8
  database: monster_production
  pool: 5
  timeout: 5000
